on:
  - push
  - pull_request

jobs:
  qwik-build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      deployments: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v1
