on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  qwik-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: corepack enable
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build
